export default {
    icCurLoc: require('../../assets/images/Oval.png'),
    icGreenMarker: require("../../assets/images/greenMarker.png"),
    greenIndicator: require("../../assets/images/greenIndicator.png"),
    icBike: require("../../assets/images/Oval.png"),
    star: require("../../assets/images/star.png"),
    starFilled: require("../../assets/images/starFilled.png"),
    verification: require("../../assets/images/verification.jpg"),
    check: require("../../assets/images/check.jpg"),
    dingdong: require("../../assets/images/dingdong.jpg"),
    defaultpic: require("../../assets/images/defaultpic.jpg"),
penIcon: require("../../assets/images/penIcon.png"),
greenCheckIcon: require("../../assets/images/greenCheckIcon.png"),
redCautionIcon: require("../../assets/images/redCautionIcon.png"),
xcircle: require("../../assets/images/xcircle.png"),
bluePin: require("../../assets/images/bluePin.jpg"),
logo: require('../../assets/images/logo.png'),
rating: require('../../assets/images/rating.png'),
}